# Generated by Django 4.2 on 2023-10-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'المدونة',
            },
        ),
    ]
