# Generated by Django 4.2 on 2023-11-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_blog_date_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'المدونة', 'verbose_name_plural': 'المدونات'},
        ),
    ]
