# Generated by Django 4.2 on 2023-11-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='background_img_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(verbose_name='لينك الفيديو'),
        ),
    ]
