# Generated by Django 4.2 on 2023-11-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_background_img_link_alter_blog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='background_img_link',
            field=models.URLField(verbose_name='لينك صورة الفيديو'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
    ]
