# Generated by Django 4.2 on 2023-11-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'صورة المعرض', 'verbose_name_plural': 'صور المعرض'},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='الصورة'),
        ),
    ]
