# Generated by Django 4.2 on 2023-11-02 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customers_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='CustomersFeedBacks',
        ),
    ]
