# Generated by Django 4.2 on 2023-11-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_customers_customersfeedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='الوظيفة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فيس بوك')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='يوتيوب')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='تويتر')),
            ],
            options={
                'verbose_name': 'عضو الفريق',
                'verbose_name_plural': 'أعضاء الفريق',
            },
        ),
    ]
