# Generated by Django 4.2 on 2023-11-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='الصورة'),
            preserve_default=False,
        ),
    ]
